In [12]:
import numpy as np
x = np.array([
    [1, 1, 0],
    [1, 2, 1],
    [1, 3, 2],
    [1, 2, 6]
])

y = np.array([[1, 0, 2, 1]]).T

pi = np.array([
    [1, 1, 0, 0, 1, 0],
    [1, 2, 1, 2, 4, 1],
    [1, 3, 2, 6, 9, 4],
    [1, 2, 6, 12, 4, 36]
])

print('x : \n{0}'.format(x)); print('\n')
print('y : \n{0}'.format(y)); print('\n')
print('pi : \n{0}'.format(pi))

x : 
[[1 1 0]
 [1 2 1]
 [1 3 2]
 [1 2 6]]


y : 
[[1]
 [0]
 [2]
 [1]]


pi : 
[[ 1  1  0  0  1  0]
 [ 1  2  1  2  4  1]
 [ 1  3  2  6  9  4]
 [ 1  2  6 12  4 36]]


In [16]:
# Right inverse for polynomial 2
w_0 = pi.T
w_1 = np.dot(pi,pi.T)
w_2 = np.linalg.inv(w_1)
w_3 = np.dot(w_0,w_2)
w = np.dot(w_3,y)
err = w.sum()

print('w : \n{0}'.format(w));print('\n')
print('Right inverse : {0}'.format(err))


# left inverse for linear
# w_0 = np.dot(x.T,x)
# w_1 = np.linalg.inv(w_0)
# w_2 = np.dot(w_1,x.T)
# w = np.dot(w_2,y)
# err = w.sum()

# print('w : \n{0}'.format(w));print('\n')
# print('left inverse : {0}'.format(err))

w : 
[[ 1.5       ]
 [-1.10833333]
 [-3.18055556]
 [ 0.57222222]
 [ 0.60833333]
 [ 0.31944444]]


Right inverse : -1.2888888888888927
